# Generated by Django 4.2.3 on 2023-07-31 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inhabitant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailynutrition",
            name="dateNutrition",
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
