# Generated by Django 4.2.3 on 2023-07-31 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inhabitant", "0002_alter_dailynutrition_datenutrition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailynutrition",
            name="dateNutrition",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
