# Generated by Django 4.2.3 on 2023-07-31 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inhabitant", "0005_alter_inhabitant_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailynutrition",
            name="dateNutrition",
        ),
        migrations.AddField(
            model_name="dailynutrition",
            name="dateStamp",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
