# Generated by Django 4.2.3 on 2023-07-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inhabitant", "0006_remove_dailynutrition_datenutrition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailynutrition",
            name="dailyNutrition",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
