# Generated by Django 4.2.3 on 2023-07-31 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typeration",
            name="rationPack",
        ),
        migrations.AddField(
            model_name="rationpack",
            name="typeRation",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="RationPack",
                to="container.typeration",
            ),
        ),
        migrations.AddField(
            model_name="typeration",
            name="rationImg",
            field=models.ImageField(default=None, upload_to=""),
        ),
        migrations.AlterField(
            model_name="container",
            name="rationPacks",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(25),
                    django.core.validators.MinLengthValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rationpack",
            name="container",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="RationPack",
                to="container.container",
            ),
        ),
        migrations.AlterField(
            model_name="typeration",
            name="rationType",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name="typeration",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
