# Generated by Django 4.2.3 on 2023-07-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "container",
            "0002_remove_typeration_rationpack_rationpack_typeration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrientcontent",
            name="ration",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="NutrientContent",
                to="container.typeration",
            ),
        ),
    ]
