# Generated by Django 4.2.3 on 2023-07-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0003_alter_nutrientcontent_ration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="rationPacks",
            field=models.IntegerField(default=1),
        ),
    ]
