# Generated by Django 4.2.3 on 2023-07-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0004_alter_container_rationpacks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeration",
            name="rationImg",
            field=models.ImageField(blank=True, default=None, upload_to=""),
        ),
    ]
