# Generated by Django 4.2.3 on 2023-07-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0005_alter_typeration_rationimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rationpack",
            name="raiotns",
            field=models.IntegerField(default=1),
        ),
    ]
