# Generated by Django 4.2.3 on 2023-07-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0006_alter_rationpack_raiotns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nutrientcontent",
            old_name="containtsDsairy",
            new_name="containtsDairy",
        ),
        migrations.AlterField(
            model_name="nutrientcontent",
            name="ration",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="NutrientContent",
                to="container.typeration",
            ),
        ),
    ]
