# Generated by Django 4.2.3 on 2023-08-05 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0005_dasher_currentlocation_dasher_desiredlocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dasher",
            name="currentLocation",
        ),
        migrations.RemoveField(
            model_name="dasher",
            name="desiredLocation",
        ),
    ]
