# Generated by Django 4.2.3 on 2023-08-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0003_alter_typeration_rationid"),
        ("storage", "0006_remove_dasher_currentlocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mover",
            name="containerHeld",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Mover",
                to="container.container",
            ),
        ),
    ]
