# Generated by Django 4.2.3 on 2023-08-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0003_alter_typeration_rationid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("facilityID", models.AutoField(primary_key=True, serialize=False)),
                ("locationX", models.IntegerField(default=0)),
                ("locationY", models.IntegerField(default=0)),
                (
                    "typeFacility",
                    models.CharField(
                        choices=[
                            ("Storage", "Storage"),
                            ("Living", "Living"),
                            ("Other", "Other"),
                        ],
                        default="Storage",
                        max_length=64,
                    ),
                ),
            ],
        ),
    ]
