# Generated by Django 4.2.3 on 2023-08-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0005_container_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="typeFacility",
            field=models.CharField(
                choices=[
                    ("Storage", "Storage"),
                    ("Living", "Living"),
                    ("Sorting Area", "Sorting Area"),
                    ("Other", "Other"),
                ],
                default="Storage",
                max_length=64,
            ),
        ),
    ]
