# Generated by Django 4.2.3 on 2023-08-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dasher",
            fields=[
                ("dasherID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Stopped", "Stopped"),
                            ("In-Progress", "In-Progress"),
                        ],
                        default="Stopped",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageFacility",
            fields=[
                (
                    "storageFacilityID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("lengthX", models.IntegerField(default=100)),
                ("lengthY", models.IntegerField(default=100)),
                ("heightZ", models.IntegerField(default=100)),
            ],
        ),
    ]
