# Generated by Django 4.2.3 on 2023-08-02 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0003_alter_typeration_rationid"),
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivingFacility",
            fields=[
                (
                    "livingFacilityID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("lengthX", models.IntegerField(default=100)),
                ("lengthY", models.IntegerField(default=100)),
                ("heightZ", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="Transit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mover",
            fields=[
                ("moverID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Stopped", "Stopped"),
                            ("In-progress", "In-progress"),
                        ],
                        default="Stopped",
                        max_length=64,
                    ),
                ),
                (
                    "containerHeld",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="container.container",
                    ),
                ),
                (
                    "locationMover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="storage.storagefacility",
                    ),
                ),
            ],
        ),
    ]
