# Generated by Django 4.2.3 on 2023-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0004_remove_livingfacility_heightz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dasher",
            name="currentLocation",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="dasher",
            name="desiredLocation",
            field=models.CharField(default=None, max_length=64),
        ),
    ]
