# Generated by Django 4.2.3 on 2023-08-05 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0009_alter_dasher_rationheld"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dasher",
            name="rationHeld",
        ),
    ]
