# Generated by Django 4.2.3 on 2023-08-07 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0011_dasher_rationheld"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("FacilityID", models.AutoField(primary_key=True, serialize=False)),
                ("locationX", models.IntegerField(default=0)),
                ("locationY", models.IntegerField(default=0)),
                (
                    "typeFacility",
                    models.CharField(
                        choices=[
                            ("Storage", "Storage"),
                            ("Living", "Living"),
                            ("Other", "Other"),
                        ],
                        default="Storage",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LivingFacility",
        ),
        migrations.DeleteModel(
            name="Transit",
        ),
        migrations.AlterField(
            model_name="dasher",
            name="status",
            field=models.CharField(
                choices=[("Stopped", "Stopped"), ("In-Progress", "In-Progress")],
                default="Stopped",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="mover",
            name="locationMover",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="storage.facility"
            ),
        ),
        migrations.DeleteModel(
            name="StorageFacility",
        ),
    ]
