# Generated by Django 4.2.3 on 2023-08-07 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0012_facility_delete_livingfacility_delete_transit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dasher",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="storage.facility",
            ),
        ),
    ]
