# Generated by Django 4.2.3 on 2023-08-08 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0013_dasher_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facility",
            old_name="FacilityID",
            new_name="facilityID",
        ),
    ]
