# Generated by Django 4.2.3 on 2023-08-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0007_alter_container_location"),
        ("storage", "0014_rename_facilityid_facility_facilityid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dasher",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="container.facility",
            ),
        ),
        migrations.AlterField(
            model_name="mover",
            name="locationMover",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="container.facility"
            ),
        ),
        migrations.DeleteModel(
            name="Facility",
        ),
    ]
