# Generated by Django 4.2.3 on 2023-08-01 21:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inhabitant",
            fields=[
                ("firstName", models.CharField(max_length=64)),
                ("lastName", models.CharField(max_length=64)),
                (
                    "inhabitantID",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Healthy", "Healthy"),
                            ("Sick", "Sick"),
                            ("Recovering", "Recovering"),
                            ("Injured", "Injured"),
                            ("Deceased", "Deceased"),
                        ],
                        default="Healthy",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dailyNutrition", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("dateStamp", models.DateField(default=datetime.datetime.today)),
                ("timeStamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "caloriesConsumed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fatConsumed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sodiumConsumed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fiberConsumed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "proteinConsumed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("isVegetarian", models.BooleanField(default=False)),
                ("allergyGluten", models.BooleanField(default=False)),
                ("allergyDairy", models.BooleanField(default=False)),
                (
                    "inhabitant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Nutrition",
                        to="inhabitant.inhabitant",
                    ),
                ),
            ],
        ),
    ]
