# Generated by Django 4.2.3 on 2023-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inhabitant", "0002_remove_dailynutrition_allergydairy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailynutrition",
            name="foodEaten",
            field=models.TextField(null=True),
        ),
    ]
