# Generated by Django 4.2.3 on 2023-08-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inhabitant", "0003_dailynutrition_foodeaten"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailynutrition",
            name="foodEaten",
            field=models.TextField(blank=True, null=True),
        ),
    ]
