# Generated by Django 4.2.3 on 2023-08-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "containerID",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("rationPacks", models.IntegerField(default=1)),
                (
                    "sensorContainer",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "sensorID",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("coordinateX", models.IntegerField()),
                ("coordinateY", models.IntegerField()),
                ("coordinateZ", models.IntegerField()),
                ("status", models.CharField(max_length=64)),
                ("temperature", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TypeRation",
            fields=[
                (
                    "rationID",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "rationImg",
                    models.ImageField(blank=True, default=None, upload_to=""),
                ),
                ("rationType", models.CharField(default=None, max_length=64)),
                ("weight", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RationPack",
            fields=[
                (
                    "rationPackID",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("rations", models.IntegerField(default=1)),
                (
                    "sensorRationPack",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "container",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="RationPack",
                        to="container.container",
                    ),
                ),
                (
                    "typeRation",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="RationPack",
                        to="container.typeration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NutrientContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories", models.IntegerField()),
                ("fat", models.IntegerField()),
                ("sodium", models.IntegerField()),
                ("fiber", models.IntegerField()),
                ("protein", models.IntegerField()),
                ("isPlantBased", models.BooleanField(default=False)),
                ("isOrganic", models.BooleanField(default=False)),
                ("containtsGluten", models.BooleanField(default=True)),
                ("containtsDairy", models.BooleanField(default=True)),
                (
                    "ration",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="NutrientContent",
                        to="container.typeration",
                    ),
                ),
            ],
        ),
    ]
