# Generated by Django 4.2.3 on 2023-08-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="containerID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
