# Generated by Django 4.2.3 on 2023-08-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0002_alter_container_containerid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeration",
            name="rationID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
