# Generated by Django 4.2.3 on 2023-08-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0004_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="location",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.PROTECT,
                to="container.facility",
            ),
        ),
    ]
