# Generated by Django 4.2.3 on 2023-08-24 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0011_alter_typeration_mealtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Container",
                to="container.facility",
            ),
        ),
    ]
